{
  "errors": [
    {
      "test": "test_send_product_tests.SendProductTests.test_send_product_nodes_tests",
      "traceback": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py\", line 591, in run\n    self._callTestMethod(testMethod)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py\", line 549, in _callTestMethod\n    method()\n  File \"/Users/sarahhoover/PycharmProjects/G01.2023.T04.EG3/src/unittest/python/test_send_product_tests.py\", line 67, in test_send_product_nodes_tests\n    for filename in os.listdir(directory):\nFileNotFoundError: [Errno 2] No such file or directory: 'send_product_tests/json_decode_error'\n"
    }
  ],
  "failures": [],
  "tests-run": 34
}